version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: "sunday"
    open-pull-requests-limit: 5
    reviewers:
      - yechs
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
      include: "scope"
