import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  kbSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    // 'intro',
    // {
    //   type: 'category',
    //   label: 'AI Engineering',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'AI-engineering',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Software Engineering',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'software',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Web Development',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'webdev',
    //     },
    //   ],
    // },
  ],
};

export default sidebars;
