name: Deploy to yechs.github.io

on:
  push:
    branches:
      - main

concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  quality:
    uses: ./.github/workflows/quality.yaml

  deploy:
    name: Deploy to yechs.github.io
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
        with:
          # fetch all commit history so "Last Updated" field will be accurate
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: master
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm run deploy
