name: Deploy to yechs.github.io
on:
  push:
    branches:
      - main
env:
  NODE_VERSION: '20'

jobs:
  lint:
    name: Syntax & Format Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Uses Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Check errors with ESLint
        run: yarn run lint
      - name: Check format with Prettier
        run: yarn run format
      - name: Test Build
        run: yarn run build

  deploy:
    name: Deploy to yechs.github.io
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch all commit history so "Last Updated" field will be accurate
          fetch-depth: 0
      - name: Uses Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: master
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          yarn run deploy
